# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine
RUN apk update && \
    apk add --no-cache make=4.4.1-r2 &&\
    adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY requirements requirements
COPY test.sh Makefile .pylintrc .coveragerc pytest.ini ./

RUN python -m venv .venv && \
    .venv/bin/pip3 install -r requirements/test.txt && \
    chmod +x test.sh && \
    chown -R microblog:microblog ./

ENV FLASK_APP microblog.py

USER microblog

EXPOSE 5000
ENTRYPOINT ["./test.sh"]