# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine
WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN <<-EOF
    python -m venv .venv
    adduser -D microblog
    .venv/bin/pip3 install -r requirements.txt
    chmod +x boot.sh
    chown -R microblog:microblog ./
EOF

ENV FLASK_APP microblog.py
USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]