FROM python:3.8-alpine

RUN adduser -D microblog
WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

ENV FLASK_APP microblog.py

RUN python -m venv .venv &&\
    .venv/bin/pip3 install -r requirements.txt &&\
    chmod +x boot.sh &&\
    chown -R microblog:microblog ./

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]